name: "CI"

on:
  pull_request:
    branches:
      - main
env:
  GO_VERSION: 1.19

jobs:
  ci:
    name: "Run format and linter"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        go-version: ${{ env.GO_VERSION}}

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run lint staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.2"
        install-go: false
